### ISSUE TITLE
ElasticSearch 2.3.1 support

### ISSUE THREAD

**Issue by hun7err** [jlinn/elasticsearch-analysis-url#5]
Hello, I've tried to add the plugin in ES 2.3.1 but as ElasticSearch lacks backward compatibility the installation has failed. Would it be possible for you to add 2.3.1 support/verify whether there are any changes between 2.3.0 and 2.3.1? It would be great if you could also add an sha1/md5 checksum as Elastic seems to complain about that as well (I do realise it's only a warning, but leaving it as it is could pose a risk to the infrastructure our database is a part of).

Thanks in advance for any help.

**Comment by jlinn** [comment]
I just published releases for ES 2.3.1 and 2.3.2.  As far as this plugin is concerned, nothing has changed from 2.3.0 through 2.3.2, but the plugin installer checks to ensure that the plugin was compiled against the proper ES version, which results in the error you are seeing.  

I added md5 and sha1 files, as well.  Hopefully the plugin installer is able to find them.

**Comment by hun7err** [comment]
Thanks a lot! Although it seems to fail the checksum check:

`ERROR: incorrect hash (SHA1), file hash: [bddfff04b9ec3faa15a86fbb94ade47dd954acff], expected: [bddfff04b9ec3faa15a86fbb94ade47dd954acff *elasticsearch-analysis-url-2.3.1.zip]`

**Comment by jlinn** [comment]
Hmm.. Odd.  Give it a shot now.

**Comment by hun7err** [comment]
Still the same error, although a slightly different expected value:

`ERROR: incorrect hash (SHA1), file hash: [bddfff04b9ec3faa15a86fbb94ade47dd954acff], expected: [bddfff04b9ec3faa15a86fbb94ade47dd954acff  elasticsearch-analysis-url-2.3.1.zip]`

**Comment by jlinn** [comment]
Ok, I think I finally figured it out.  I tested it with v2.3.2, and it worked.

**Comment by hun7err** [comment]
Works like a charm. Thanks a lot!
